<?php


namespace Piwik\Plugins\KafkaProducer;


class Http extends \Piwik\Http
{
    public static function sendHttpRequest($aUrl, $timeout, $userAgent = null, $destinationPath = null, $followDepth = 0, $acceptLanguage = false, $byteRange = false, $getExtendedInfo = false, $httpMethod = 'GET', $httpUsername = null, $httpPassword = null)
    {
        Utils::console_log("Request sent");
        return parent::sendHttpRequest($aUrl, $timeout, $userAgent, $destinationPath, $followDepth, $acceptLanguage, $byteRange, $getExtendedInfo, $httpMethod, $httpUsername, $httpPassword); // TODO: Change the autogenerated stub
    }
}
