<?php

namespace Piwik\Plugins\KafkaProducer;

use Piwik\Tracker;
use Piwik\Tracker\RequestSet;
use Piwik\Tracker\Handler;

class RequestHandler extends Handler
{
    public function process(Tracker $tracker, RequestSet $requestSet)
    {
        parent::process($tracker, $requestSet); // TODO: Change the autogenerated stub
    }


    public function onStartTrackRequests(Tracker $tracker, RequestSet $requestSet)
    {
        parent::onStartTrackRequests($tracker, $requestSet); // TODO: Change the autogenerated stub
    }

}

